import type { DailyCheckData } from './types';

export function createEmptyDailyCheckData(): DailyCheckData {
  return {
    style_po_info: {
      style: '',
      po: '',
      cpo: '',
      brand: '',
      description: '',
      colors_qty: '',
      division: '',
      last_x_factory_date: '',
    },
    visit_details: {
      date: '',
      inspector: '',
      factory: '',
      audit_stage: '',
      lines: '',
      sewer_headcount: 0,
      machines_allocated: 0,
      machines_running: 0,
    },
    document_audit: {
      tech_pack: '',
      po: '',
      pps_sample: '',
      fabric: '',
      accessory: '',
      trim_card: '',
      packing: '',
      size_spec: '',
    },
    production_status: {
      order_qty: 0,
      cutting: 0,
      sewing: 0,
      finishing: 0,
      packed: 0,
      balance_workshop: 0,
      in_house_vs_sub: '',
      ex_factory_date: '',
    },
    in_process_checks: {},
    accessories_check: {},
    defect_checklist: {},
    aql_inspection: {
      pcs_available: 0,
      pcs_inspected: 0,
      aql_level: '',
      sample_source: '',
      total_majors: 0,
      total_minors: 0,
      pcs_rejected: 0,
      defective_percent: '',
      inspection_result: '',
      acceptance: '',
    },
    bulk_conformity: {},
    photo_journal: {
      cutting_floor: '',
      sewing_line: '',
      pressing_finishing: '',
      labelling: '',
      packing_carton: '',
      defect: '',
      colour_shading: '',
      measurement: '',
    },
    meeting_cap: {
      meeting_notes: '',
      cap: '',
      overall_result: '',
      system_report_issued: false,
      detailed_comments: '',
      action_by_vendor: '',
      inspector_signature: '',
      factory_signature: '',
      date: '',
    },
  };
}
